### PR TITLE
Animation bugfixes

### PR DESCRIPTION
**Pull request by coolasjake**
- Forwards Jump changed
- Jump Delay added
- Landing Delay added
- Climb animation set up
- Earthquake bug fixed (but transferred to camera if smoothing is on)
- Superman bug fixed
- Animation resetting bug fixed
- Continuous animation bugs fixed (landing, jumping, running)

Test:
* Move around world in all sorts of ways and try to spot any bugs with animation
* Same but for jittering (beach near first cave used to do it consistently)
* Jump while moving forwards = speed is much lower (can be changed in settings now too)
* Climb something = climb animation
* Jump = there is a small delay so the animation lines up
* Jump/Climb while landing = it is delayed

Notes/Bugs:
> Jittering still happens when the camera has significant smoothing

### CODE REVIEW

**Review by 102747419 — APPROVED** [review]
Looks good!

**Comment by coolasjake** [comment]
[Land Jump Animation sometimes doesn't work](https://trello.com/c/oOBusEbI/163-land-jump-animation-sometimes-doesnt-work)

**Comment by coolasjake** [comment]
[Hit edge stops movement (animation bug)](https://trello.com/c/IJzsxjhN/169-hit-edge-stops-movement-animation-bug)

**Comment by coolasjake** [comment]
[Jump delay, landing slowdown](https://trello.com/c/NJVH1dnu/171-jump-delay-landing-slowdown)

**Comment by coolasjake** [comment]
[Superman Bug](https://trello.com/c/NoW5twsC/170-superman-bug)

**Pull request merged**
