### PR TITLE
Music and ambience triggers

### PR DESCRIPTION
**Pull request by 102747419**
This PR adds two cube trigger areas: MusicTrigger and AmbienceTrigger. Each can be scaled and positioned to fit anywhere on the map. Music and ambient noises can be specified in the respective trigger and continuously loop. Only one music track can play at a time and it fades out before a new track plays. Any number of ambience triggers can be overlapped to layer on several ambient sounds. The music and ambience volume can be adjusted using the music and SFX volume sliders in the options menu.

Steps to test:
1. Be on Jordan scene
2. See where the music and ambient triggers are located in the scene
3. Play the game and walk between the trigger areas
* I even tested if the squirrel spawns in a trigger area

Preview:
* Enable sound of course
* The trigger areas were made visible for demonstration

https://user-images.githubusercontent.com/62001991/133990242-c35c6e01-b1a4-44c4-92cf-9c347fc7c046.mp4

### CODE REVIEW

**Comment by 102747419** [comment]
[Implement music and ambience](https://trello.com/c/8dgDAeSb/144-implement-music-and-ambience)

**Review by tobyamiel — APPROVED** [review]
after rigorous testing, i have found that this is an incredible system and personally fixed many bugs myself. thank you and goodnight.

**Review by coolasjake — APPROVED** [review]
System works perfectly as expected.

Code has some strange things:
- Disabling mesh renderers on audio/music triggers (just delete them in scene?)
- Player validation checks the layer, but the preferred method is to place the triggers in a layer that only collides with the player layer, which would make this check obsolete.
- Music/Ambiance triggers seem almost identical - is polymorphism viable?

**Comment by 102747419** [comment]
I will do the second point and consider doing the first point before we merge this. The third point wouldn't be good because music and ambience behave differently.

**Comment by 102747419** [comment]
Using gizmos instead of the mesh renderer for making the triggers visible in the scene is worse. You can't gauge depth with gizmos.

**Pull request merged**
